apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
  namespace: NAMESPACE
data:
  KC_HTTPS_CERTIFICATE_FILE: /etc/certs/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/certs/tls.key
  KC_HOSTNAME: FQDN
  KC_HOSTNAME_ADMIN: ADMIN_FQDN
  KC_DB: postgres
  KC_DB_URL_HOST: postgresql-service
  KC_DB_URL_PORT: "5432"
  # We need to enable http, as we are behind an ingress
  KC_HTTP_ENABLED: "true"
  # TODO Maybe also enable load shedding
  # KC_HTTP_MAX_QUEUED_REQUESTS: 2000
