# Hostname config:
# https://www.keycloak.org/server/hostname#_exposing_the_administration_console_on_a_separate_hostname
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
  namespace: NAMESPACE
data:
  KC_HTTPS_CERTIFICATE_FILE: /etc/certs/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/certs/tls.key
  # We trust our traefik to properly set headers
  # see: https://www.keycloak.org/server/reverseproxy & https://www.keycloak.org/server/hostname
  # and: https://doc.traefik.io/traefik/getting-started/faq/#what-are-the-forwarded-headers-when-proxying-http-requests
  KC_HOSTNAME: FQDN
  KC_PROXY_HEADERS: xforwarded
  KC_DB: postgres
  KC_DB_URL_HOST: postgresql-service
  KC_DB_URL_PORT: "5432"
  # We need to enable http, as we are behind an ingress
  KC_HTTP_ENABLED: "true"
  # TODO Maybe also enable load shedding
  # KC_HTTP_MAX_QUEUED_REQUESTS: 2000
