apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: NAMESPACE
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      # TODO: Add Resource allocations
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:20.0.3
        imagePullPolicy: IfNotPresent
        args:
        - start
        volumeMounts:
        - name: keycloak-cert
          mountPath: /etc/certs
          readOnly: true
        envFrom:
          - configMapRef:
              name: keycloak-env
          - secretRef:
              name: keycloak-secret
        ports:
        - name: http
          containerPort: 8080
      volumes:
        - name: keycloak-cert
          secret:
            secretName: keycloak
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key

