apiVersion: v1
kind: Service
metadata:
  name: keycloak-management-interface
  labels:
    service: keycloak-management-interface
  namespace: NAMESPACE
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 9000
  selector:
    app: keycloak