apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: postgres
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: "psql-user"
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "psql-pw"
          ports:
            - containerPort: 5432
              name: postgresql
          cmd:
          volumeMounts:
            - name: postgres-config-volume
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
              readOnly: true
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
